### ISSUE TITLE
The app is crashing

### ISSUE THREAD

**Issue by DenerVieira** [nielsvanvelzen/tv-launcher#193]
![IMG_20231004_154442](https://github.com/nielsvanvelzen/tv-launcher/assets/66522513/d8ad70be-7bd1-494c-bf70-16f97af7df2c)

When I open the app it closes quickly I'm using Android 7.1.2 MBOX

**Comment by nielsvanvelzen** [comment]
I've just tried the [latest commit](https://github.com/nielsvanvelzen/tv-launcher/commit/e70ff47af1bb50aa81df24caafeb7207b071f44a) and it is running fine. Please share your crash logs so I can look into it.

**Comment by DenerVieira** [comment]
I installed the latest version but it keeps closing and how can I get the logs and post them here?

**Comment by nielsvanvelzen** [comment]
The app might be incompatible with Android 7. I have only tested with Android 8 and newer so far. The crash logs can be retrieved via logcat via adb.

**Comment by DenerVieira** [comment]
> `[Logcat](https://we.tl/t-lk4hilq3jJ) `

**Comment by nielsvanvelzen** [comment]
Those logs don't include anything I can work with. Make sure the app is opened in the timeframe of the logs, and preferably shrink the amount of lines.

**Comment by DenerVieira** [comment]
Ok I'll do it later

**Comment by DenerVieira** [comment]
[Logs](https://we.tl/t-tcjrjDUUsG) 

New logcat

**Comment by nielsvanvelzen** [comment]
It looks like your device is not running Android TV and the app uses an Android TV specific API. That should be relatively easy to fix.

```
10-07 20:55:29.478  1362  1362 E AndroidRuntime: FATAL EXCEPTION: main
10-07 20:55:29.478  1362  1362 E AndroidRuntime: Process: nl.ndat.tvlauncher, PID: 1362
10-07 20:55:29.478  1362  1362 E AndroidRuntime: java.lang.IllegalArgumentException: Unknown URI content://android.media.tv/watch_next_program
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:532)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:474)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at nl.ndat.tvlauncher.data.resolver.ChannelResolver.getWatchNextPrograms(ChannelResolver.kt:89)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at nl.ndat.tvlauncher.data.repository.ChannelRepository.refreshWatchNextChannels(ChannelRepository.kt:78)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at nl.ndat.tvlauncher.data.repository.ChannelRepository.refreshAllChannels(ChannelRepository.kt:57)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at nl.ndat.tvlauncher.LauncherActivity$onCreate$1$1.invokeSuspend(LauncherActivity.kt:39)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:755)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
10-07 20:55:29.478  1362  1362 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7613570, Dispatchers.Main.immediate]
```

**Comment by nielsvanvelzen** [comment]
Should be fixed now, please try again with the latest commit. Share new logs if the issue persists.

**Comment by DenerVieira** [comment]
Now it works normally
